app = "ali-express-scrapper"
primary_region = "cdg" # Paris region, but you can change this
kill_signal = "SIGINT"
kill_timeout = 30

[env]
  PORT = "8080"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false # Changed to false to prevent automatic shutdown
  auto_start_machines = true
  min_machines_running = 1 # Keep at least 1 machine running
  processes = ["app"]

[processes]
  app = "bun run server.ts"
  cron = "bun run index.ts"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024 # 1GB of RAM

# Schedule the scraper to run every 6 hours
[[scheduled_tasks]]
  command = "bun run index.ts"
  cron = "0 */6 * * *" # Every 6 hours
  processes = ["cron"]
