name: Ali Express Scraper

on:
  schedule:
    # Run every 6 hours - at minute 0 of hour 0, 6, 12, and 18
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:  # This allows manual triggering through the GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          # Install Chrome browser which will provide necessary dependencies
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          # Install additional dependencies that Puppeteer needs
          sudo apt-get install -y --fix-missing libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 libatk1.0-0 libatk-bridge2.0-0 libpangocairo-1.0-0 libgtk-3-0 libgbm1

      - name: Install dependencies
        working-directory: ./ali-express-scrapper
        run: bun install

      - name: Run scraper
        working-directory: ./ali-express-scrapper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          CI: true
          GITHUB_ACTIONS: true
        run: |
          echo "Starting scraper in CI environment"
          echo "Checking Chrome installation:"
          which google-chrome
          google-chrome --version
          echo "Running scraper..."
          bun run index.ts
