name: Ali Express Scraper

on:
  schedule:
    # Run every 6 hours - at minute 0 of hour 0, 6, 12, and 18
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:  # This allows manual triggering through the GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev libatk-bridge2.0-0 libgtk-3-0 libasound2 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libpangocairo-1.0-0 libnss3 libatk1.0-0 libcups2 libxss1 libxkbcommon0 libglib2.0-0

      - name: Install dependencies
        working-directory: ./ali-express-scrapper
        run: bun install

      - name: Run scraper
        working-directory: ./ali-express-scrapper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          CI: true
          GITHUB_ACTIONS: true
        run: bun run index.ts
